# Generated by Django 3.2.5 on 2022-09-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='descrption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='descrption_html',
            new_name='description_html',
        ),
    ]
